#!/bin/sh

STATUS="PASS"
SLEEP_TIME=3600
DESC_FILE="HOUR_DESCRIPTIONS"
TZ_FILE="TZ_MAP"

while true; do
    # Get random pair from tz_map file.
    # This is a city and country or a country and some sort of area.
    ROW=$(shuf -n 1 < "$TZ_FILE")
    echo "DEBUG: ROW: $ROW"

    BIG_AREA=$(echo "$ROW" | cut -d ' ' -f 1)
    echo "DEBUG: BIG_AREA: $BIG_AREA"

    SMALL_AREA_CAP=$(echo "$ROW" | cut -d ' ' -f 2)
    SMALL_AREA=$(shuf -i 1-"$SMALL_AREA_CAP" -n 1)
    echo "DEBUG: SMALL_AREA: $SMALL_AREA"

    # Use tzselect to turn the number pair into the actual names, and also get the time there.
    # Takes two passes, unless I can find a way to be more clever.
    # TODO make this less garbage
    TZ_CMD="$BIG_AREA \n $SMALL_AREA \n 1 \n 1 \n"

    NAME=$(echo "$TZ_CMD" | tzselect 2>/dev/null | sed -r s'/(.*)\/(.*)/\2, \1/')

    TIME_REGEX="/.*([0-9]{2}:[0-9]{2}:[0-9]{2}).*/\1/"

    TIME=$(echo "$TZ_CMD" | tzselect 2>&1 | grep "Local time" | sed -r s"$TIME_REGEX")

    echo "DEBUG: NAME: $NAME"
    echo "DEBUG: TIME: $TIME"

    # Check hour.
    HOUR=$(echo "$TIME" | sed -r s'/([0-9]{2}).*/\1/')

    echo "DEBUG: HOUR IS $HOUR"

    if [ "$HOUR" = "17" ]; then
        echo "DEBUG: It's 5 'o' clock!"
        STATUS="FAIL"
    else
        echo "DEBUG: It's not 5 'o' clock!"
        STATUS="PASS"
    fi

    DESC=$(shuf -n 1 < "$DESC_FILE")
    MSG="It's not $DESC in $NAME, it's $TIME local time."

    echo "$MSG"

    # Try again immediately if status was fail.
    # Otherwise, tweet and sleep for a while.
    if [ "$STATUS" = "PASS" ]; then
        echo "tweeting '$MSG'"
        python3 send.py "$MSG"

        echo "Sleeping for $SLEEP_TIME"
        sleep "$SLEEP_TIME"
    else
        echo "Bad!"
        sleep 1
    fi
done
